---
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
  labels:
    app: metrics-server-exporter
  name: metrics-server-exporter
  namespace: kube-system
spec:
  nodeSelector:
    dedicated: master
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: metrics-server-exporter
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      annotations:
        prometheus.io/path: "/metrics"
        prometheus.io/port: "8080"
        prometheus.io/scheme: "http"
        prometheus.io/scrape: "true"
      labels:
        app: metrics-server-exporter
    spec:
      containers:
        - image: ghouscht/metrics-server-exporter:0.0.1
          imagePullPolicy: Always
          name: metrics-server-exporter
      serviceAccountName: metrics-server-exporter
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: metrics-server-exporter
  namespace: kube-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: metrics-server-exporter
rules:
  - apiGroups:
      - metrics.k8s.io
    resources:
      - nodes
      - pods
    verbs:
      - list
      - get
  - apiGroups:
      - ""
    resources:
      - nodes
    verbs:
      - list
      - get
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: metrics-server-exporter
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: metrics-server-exporter
subjects:
  - kind: ServiceAccount
    name: metrics-server-exporter
    namespace: kube-system
